In [51]:
import numpy as np

# Define the number of states and actions
x=5
y=10
num_states = x*y
num_actions = 5
#5 actions: up, down, left, right, stay
def up(state):
    return state - y
def down(state):
    return state + y
def left(state):
    return state - 1
def right(state):
    return state + 1
def stay(state):
    return state

# Initialize the Q-table
Q = np.zeros((num_states, num_actions))

# Define the learning rate and discount factor
alpha = 0.1
gamma = 0.9

# Define the reward function
def get_reward(state, action, next_state):
    # If the robot reaches the exit, return a large positive reward
    if next_state == 49:
        return 100
    # If the robot hits an obstacle, return a negative reward
    if next_state in [2, 3, 5, 9, 15, 20, 21, 26, 45, 46, 47, 48]:
        return -100
    if next_state >= 50 or next_state < 0:
        return -100
    # Otherwise, return a small positive reward
    return 1

# Define the update rule for the Q-table
def update_Q(state, action, next_state, reward, Q, alpha, gamma):
    max_Q = max(Q[next_state, :])
    Q[state, action] = Q[state, action] + alpha * (reward + gamma * max_Q - Q[state, action])
    return Q

# Start the training loop
for i in range(10000):
    # Initialize the state and action
    state = 0
    action = np.argmax(Q[state, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))
    while state != 49:
        # Take the action and observe the next state and reward
        if action == 0:
            next_state = up(state)
        elif action == 1:
            next_state = down(state)
        elif action == 2:
            next_state = left(state)
        elif action == 3:
            next_state = right(state)
        else:
            next_state = stay(state)
        
        reward = get_reward(state, action, next_state)

        # Update the Q-table
        Q = update_Q(state, action, next_state, reward, Q, alpha, gamma)
        # Update the state and action
        if reward != -100:
            state = next_state
        action = np.argmax(Q[state, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))
print(Q)

IndexError: index 53 is out of bounds for axis 0 with size 50

In [48]:
#based on table Q, get best action for each state
best_action = np.argmax(Q, axis=1)
print(best_action)

[0 2 2 3 1 0 2 3 2 0 2 2 0 2 2 0 1 3 3 1 1 2 0 2 1 1 3 1 3 2 2 3 1 2 3 2 3
 1 2 2 3 2 2 3 1 2 3 1 1 0]


In [47]:
print(Q[47, :])
np.argmax(Q[47, :])

[ 0.  91.   0.   0.1]


1

In [16]:
Q[4, :]

array([-10.       ,  -8.9332489,  -8.9332489,  -8.9332489])

In [38]:
np.argmax(Q[state, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))

2

In [9]:
import numpy as np
import random

# Define the number of states and actions
x=6
y=6
borders=[i for i in range(0,x)]+[i for i in range(x*(y-1),x*y)]+[i*x for i in range(1,y-1)]+[(i+1)*x-1 for i in range(1,y-1)]
borders.append(x*y)
borders=borders+[20,21]
print(borders)
print(len( borders))


#list from 0 to 35
all= [i for i in range(x*y+1)]
#list of all states not in borders
states = [i for i in all if i not in borders]
print(states)

num_states = x*y+1
num_actions = 4
num_robot = 2

# Initialize the Q-table
Q=[]
for i in range(num_robot):
    Q.append(np.zeros((num_states, num_actions)))

# Define the learning rate and discount factor
alpha = 0.1
gamma = 0.9

# Define the reward function
def get_reward(state, action, next_state,target=28):

    # If the robot hits an obstacle, return a negative reward
    if next_state in borders:
        return -100
    # If the robot reaches the exit, return a large positive reward
    if next_state == target:
        return 100
    
    # Otherwise, return a small positive reward
    return -1

# Define the update rule for the Q-table
def update_Q(state, action, next_state, reward, Q, alpha, gamma):
    max_Q = max(Q[next_state, :])
    Q[state, action] = Q[state, action] + alpha * (reward + gamma * max_Q - Q[state, action])
    return Q


r1=0
r2=0
# Start the training loop
for i in range(10000):
    # Initialize the state and action
    #random start state not in borders


    state1 = random.randint(0,len(states)-1)
    state1=states[state1]
    states2=states.copy()
    states2.remove(state1)
    state2 = random.randint(0,len(states)-1)
    state2=states[state2]

    

    action1 = np.argmax(Q[0][state1, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))
    action2 = np.argmax(Q[1][state2, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))

    target = 28
    while state1 != target and state2 != target:
        # Take the action and observe the next state and reward
        if action1 == 0:#go up
            next_state1 = state1 - y
        elif action1 == 1:#go down
            next_state1 = state1 + y
        elif action1 == 2:#go left
            next_state1 = state1 - 1
        elif action1 == 3:#go right
            next_state1 = state1 + 1
        if next_state1 == state2:#if robot 1 and 2 collide
                next_state1 = x*y

        reward1 = get_reward(state1, action1, next_state1)
        Q[0] = update_Q(state1, action1, next_state1, reward1, Q[0], alpha, gamma)
        if reward1 != -100:
            state1 = next_state1

        action1 = np.argmax(Q[0][state1, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))


        if action2 == 0:
            next_state2 = state2 - y
        elif action2 == 1:
            next_state2 = state2 + y
        elif action2 == 2:
            next_state2 = state2 - 1
        elif action2 == 3:
            next_state2 = state2 + 1
        if next_state2 == state1:
                next_state2 = x*y
        

        
        reward2 = get_reward(state2, action2, next_state2)
        # Update the Q-table
        
        Q[1] = update_Q(state2, action2, next_state2, reward2, Q[1], alpha, gamma)
        # Update the state and action
        
        if reward2 != -100:
            state2 = next_state2
        
        action2 = np.argmax(Q[1][state2, :] + np.random.randn(1, num_actions) * (1. / (i + 1)))

    if state1 == target:
        r1+=1
    elif state2 == target:
        r2+=1
#print(Q)

[0, 1, 2, 3, 4, 5, 30, 31, 32, 33, 34, 35, 6, 12, 18, 24, 11, 17, 23, 29, 36, 20, 21]
23
[7, 8, 9, 10, 13, 14, 15, 16, 19, 22, 25, 26, 27, 28]


In [10]:
print(Q[0])#robot 1

[[  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [-19.         -20.14307497 -19.          39.79315702]
 [-10.         -10.          -6.88708477  47.21374331]
 [-19.         -10.252      -15.13397125  57.47957139]
 [-27.1         69.95204566 -19.19591621 -27.1       ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [-19.12210252  44.66031399 -19.         -20.76164254]
 [-13.7464174  -19.           1.38715894 -19.36643461]
 [ -0.75887265 -10.          -0.4864771   59.51838693]
 [ -0.72626811  88.93608036  -0.2319751  -10.        ]
 [  0.           0.           0.           0.        ]
 [  0.    

In [18]:
def get_path(Q, state, target):
    path = [state]
    while state != target:
        action = np.argmax(Q[state, :])
        if action == 0:
            state = state - y
        elif action == 1:
            state = state + y
        elif action == 2:
            state = state - 1
        elif action == 3:
            state = state + 1
        path.append(state)
    return path
get_path(Q[0], 7, target)

[7, 8, 9, 10, 16, 22, 28]

In [17]:
get_path(Q[1], 14, target)

[14, 15, 16, 22, 28]

In [155]:
print(r1)
print(r2)

56877
43123
